# Generated by Django 4.2.1 on 2023-05-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krupskoi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vhod',
            old_name='capital_population',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='vhod',
            old_name='capital_city',
            new_name='entry_name',
        ),
        migrations.RemoveField(
            model_name='vhod',
            name='country',
        ),
    ]
