# Generated by Django 4.2.1 on 2023-05-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupskoi', '0002_rename_capital_population_vhod_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vhod',
            name='author',
        ),
        migrations.RemoveField(
            model_name='vhod',
            name='entry',
        ),
        migrations.AddField(
            model_name='vhod',
            name='entry_code',
            field=models.BooleanField(default=False),
        ),
    ]
