# Generated by Django 4.2.1 on 2023-05-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupskoi', '0003_remove_vhod_author_remove_vhod_entry_vhod_entry_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vorota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_code', models.BooleanField(default=False)),
                ('entry_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Vhod',
            new_name='Kalitka',
        ),
    ]
